#!/usr/bin/env sh

# Run linting
npm run lint

# Run type checking
npm run build --noEmit

# Run tests
if [ -n "$STAGED_FILES" ]; then
  npm test -- --bail --findRelatedTests $STAGED_FILES
else
  npm test -- --bail
fi